[WIP, ENH] Implement minimal m-separator functionality
py-why/pywhy-graphs pull request #53
Opened 2023-02-15 16:28 UTC by jaron-lee

Fixes #34 

Changes proposed in this pull request:

- Implements a function to detect minimal m-separators (if any) in a graph

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

2023-02-15 17:12 UTC, adam2392 commented on pywhy_graphs/networkx/algorithms/causal/m_separation.py
> +def _bfs_with_marks(G, start_node, check_set):
```suggestion
# XXX: If networkx makes the corresponding function in `d_separation.py` public, then we can depend on that implementation
def _bfs_with_marks(G, start_node, check_set):
```

2023-02-16 22:01 UTC, jaron-lee commented
@adam2392 when you get a chance - I tried implementing minimal m-separators according to the Van der Zander paper. They have an example in figure 5 which I have written tests for. I have a failing test for `minimal_m_separators(G, "X", "Y", i={"Z_1"})` in that graph. 
I think I have implemented the algorithm (FINDMINSEP) correctly as it is written down in the paper, but there seems to be some issues with it generally? For example, when computing `Z''` it's possible that the algorithm would search for a path from `X` to something in `i`, but in the third line of FINDMINSEP all nodes in `i` are removed, so there aren't any paths to `i` at all. I have tried both including and excluding `i` when this happens but couldn't get things to work. Currently I am excluding `i`, but in the failing test case this means that `z` is empty and so we fail to find a minimal m-separator, even though `Z_1` is a valid minimal m-separator.

2023-02-16 22:05 UTC, jaron-lee commented
Oh I think I figured it out, there is a missing line that should read:

"Remove from G' all nodes of I" 

I should submit a PR on that paper...

2023-02-16 22:22 UTC, adam2392 commented
> Oh I think I figured it out, there is a missing line that should read:
> 
> "Remove from G' all nodes of I"
> 
> I should submit a PR on that paper...

If it ends up working, we should document the "change" relative to what's in the paper, so at least our docstring is a pseudo-source of truth :p

2023-02-17 21:14 UTC, adam2392 requested changes
I'll do a more thorough check of the algo once we fix the nitpicks. Looking good!

2023-02-17 21:14 UTC, adam2392 commented on docs/whats_new/v0.1.rst
> +- |Feature| Implement minimal m-separator function in :func:`pywhy_graphs.networkx.minimal_m_separators` with a BFS approach, by `Jaron Lee`_ (:pr:`53`)
```suggestion
- |Feature| Implement minimal m-separator function in :func:`pywhy_graphs.networkx.minimal_m_separator` with a BFS approach, by `Jaron Lee`_ (:pr:`53`)
```

2023-02-17 21:14 UTC, adam2392 commented on pywhy_graphs/networkx/algorithms/causal/m_separation.py
> +    assert z <= r, f"Separating set {z} should be no larger than maximum set {r}"
These have to be `if` statements that result in a e.g. RuntimeError. tldr: assert statements don't always work in Python code if it's compiled into a binary.

2023-02-17 21:14 UTC, adam2392 commented on pywhy_graphs/networkx/algorithms/causal/m_separation.py
> +    assert z <= r, f"Separating set {z} should be no larger than maximum set {r}"
And then a corresponding test for the error cases to complete coverage

2023-02-20 16:44 UTC, jaron-lee commented
@adam2392 I think i basically fixed all the errors, but there is this one CI test failing. Doesn't look related to the code I've written. I vaguely recall we had this on another PR but I don't remember the fix.

2023-02-20 16:54 UTC, adam2392 commented
> @adam2392 I think i basically fixed all the errors, but there is this one CI test failing. Doesn't look related to the code I've written. I vaguely recall we had this on another PR but I don't remember the fix.

Pushing a fix

2023-02-20 16:59 UTC, adam2392 approved these changes
LGTM minus some doc fixes.

2023-02-20 16:59 UTC, adam2392 commented on pywhy_graphs/networkx/algorithms/causal/m_separation.py
> +        Name of the directed edge, default is directed.
```suggestion
        Name of the directed edge, default is 'directed'.
```

2023-02-20 16:59 UTC, adam2392 commented on pywhy_graphs/networkx/algorithms/causal/m_separation.py
> +        Name of the bidirected edge, default is bidirected.
```suggestion
        Name of the bidirected edge, default is 'bidirected'.
```

2023-02-20 16:59 UTC, adam2392 commented on pywhy_graphs/networkx/algorithms/causal/m_separation.py
> +        Name of the undirected edge, default is undirected.
```suggestion
        Name of the undirected edge, default is 'undirected'.
```

2023-02-20 16:59 UTC, adam2392 commented on pywhy_graphs/networkx/algorithms/causal/m_separation.py
> +
```suggestion
```

2023-02-20 17:00 UTC, adam2392 commented
https://output.circle-artifacts.com/output/job/622f3036-7e58-4476-9a6a-f9aa8cfa376c/artifacts/0/dev/api.html#networkx-experimental-functionality

2023-02-20 17:02 UTC, adam2392 commented
Will merge this once CIs give green light

2023-02-20 17:23 UTC, merged

2023-02-20 17:23 UTC, adam2392 commented
Thanks @jaron-lee !