Graph title
py-why/pywhy-graphs pull request #71
Opened 2023-03-30 18:12 UTC by aryan26roy

Closes #23 

Changes proposed in this pull request:

- Adds a keyword argument for graph labels to viz.draw

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

2023-03-30 18:16 UTC, adam2392 reviewed
Can you add a unit-test and also add a changelog entry to `docs/whats_new/v0.1.rst`?

2023-03-30 18:16 UTC, aryan26roy commented
Sure! Just getting used to the procedure for this repo.

2023-03-30 18:52 UTC, adam2392 requested changes
Thanks for the PR! It mostly looks good minus a few nitpicks. 

One last thing: Can you also augment the existing example in `examples/` to show off the label feature? E.g. in https://output.circle-artifacts.com/output/job/e94330e9-bd6c-4d83-ae14-8ed903121326/artifacts/0/dev/auto_examples/visualization/draw_and_compare_graphs_with_same_layout.html#sphx-glr-auto-examples-visualization-draw-and-compare-graphs-with-same-layout-py it would be great to see some sensible titles of the different graphs.

You can build the documentation locally to test it out and what it looks like by following the Contributing.md doc. Lmk if you have any issues!

2023-03-30 18:52 UTC, adam2392 commented on docs/whats_new/v0.1.rst
> +- |Feature| Add keyword argument for graph lables in :func:`pywhy_graphs.viz.draw`, by `Aryan Roy`_ (:pr:`71`)
```suggestion
- |Feature| Add keyword argument for graph labels in :func:`pywhy_graphs.viz.draw`, by `Aryan Roy`_ (:pr:`71`)
```

2023-04-01 07:25 UTC, aryan26roy commented on pywhy_graphs/viz/tests/test_draw.py
> +    assert "label=test" in dot.source
Sure!

2023-04-01 07:54 UTC, aryan26roy commented
Hey @adam2392 I think I implemented all the changes you requested. Sorry for the delay though.

2023-04-02 17:54 UTC, adam2392 approved these changes
LGTM once CI passes

2023-04-03 02:33 UTC, merged

2023-04-03 02:33 UTC, adam2392 commented
Thanks @aryan26roy !